name: Create Tag on Specific Date and Time

on:
  schedule:
    # Runs every day at 4:48 PM UTC
    - cron: '48 16 * * *'

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and Push Tag
        run: |
          # Ensure we are on the master branch (default branch for this repo)
          git checkout master

          # Get the latest changes
          git pull

          # Define the target date (YYYYMMDD)
          TARGET_DATE="20250203"

          # Get the current date in YYYYMMDD format
          CURRENT_DATE=$(date +'%Y%m%d')

          # Get the current time in HHMM format
          CURRENT_TIME=$(date +'%H%M')

          # Define the target time (4:48 PM)
          TARGET_TIME="1648"

          # Define the version number
          VERSION="v1.56"

          # Check if the current date and time match the target date and time
          if [ "$CURRENT_DATE" = "$TARGET_DATE" ] && [ "$CURRENT_TIME" = "$TARGET_TIME" ]; then
            # Generate the tag name using the target date and version number
            TAG="rr-${TARGET_DATE}-${VERSION}"

            # Create an annotated tag with a message
            git tag -a $TAG -m "Stable version for Loginform build"

            # Push the tag to the remote repository
            git push origin $TAG

            echo "Tag $TAG created and pushed successfully."
          else
            echo "Current date and time $CURRENT_DATE $CURRENT_TIME do not match the target date and time $TARGET_DATE $TARGET_TIME. No tag created."
          fi
