name: Create Tag at Specified Time

on:
  schedule:
    # Runs 3 minutes from now (update with the correct UTC time)
    - cron: '*/3 * * * *'  # Runs every 3 minutes for testing

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and Push Tag
        run: |
          # Ensure we are on the main branch (adjust if needed)
          git checkout master

          # Get the latest changes
          git pull

          # Define the version number
          VERSION="v1.07"

          # Generate the tag name using the current date and version number
          TAG="rr-$(date +'%Y%m%d-%H%M')-${VERSION}"

          # Create an annotated tag with a message
          git tag -a $TAG -m "Stable version for Loginform build"

          # Push the tag to the remote repository
          git push origin $TAG

          echo "Tag $TAG created and pushed successfully."
