name: Create Tag at Specified Time

on:
  schedule:
    # Runs every 3 minutes
    - cron: '*/3 * * * *'

  workflow_dispatch:  # Allows manual trigger

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and Push Tag If Date & Time Match
        run: |
          # Ensure we are on the master branch
          git fetch --all
          git checkout master || git checkout -b master
          git pull origin master

          # Define the target dates (YYYYMMDD)
          TARGET_DATES=("20250204" "20250218" "20250225" "20250318" "20250415" "20250422")

          # Get the current date and time
          CURRENT_DATE=$(date -u +'%Y%m%d')

          # Define the version number
          VERSION="v1.88"

          # Check if the current date is in the list and time matches
          for TARGET_DATE in "${TARGET_DATES[@]}"; do
            if [[ "$CURRENT_DATE" == "$TARGET_DATE" ]]; then
              # Generate the tag name
              TAG="rr-${TARGET_DATE}-${VERSION}"

              # Create an annotated tag
              git tag -a "$TAG" -m "Stable version for Loginform build"

              # Push the tag
              git push origin "$TAG"

              echo "Tag $TAG created and pushed successfully."
              exit 0  # Stop further iterations
            fi
          done

          echo "No matching date and time found. No tag created."
