name: Create Tag at Specified Time for sr

on:
  schedule:
    # Runs on specific dates in 2025 at 07:00 AM UTC (12:30 PM IST)
    - cron: '0 7 19 2 *'
    - cron: '0 7 16 4 *'
    - cron: '0 7 17 9 *'
    - cron: '0 7 12 11 *'

  workflow_dispatch:  # Allows manual trigger

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Tag If Date Matches
        run: |
          # Ensure we are on the correct branch
          git fetch --all
          git checkout develop

          # Get the latest changes
          git pull origin develop
                    
          # Get the current date in YYYYMMDD format
          CURRENT_DATE=$(date -u +'%Y%m%d')  # Use UTC time

          # Define the version number
          VERSION="1.0"
         
          # Generate the tag name with the Release date
          TAG="sr-${CURRENT_DATE}-v${VERSION}"

          # Create an annotated tag
          git tag -a $TAG -m "Stable version for Advanced Badgeting Standard Release Build"

          # Push the tag
          git push origin $TAG

          echo "Tag $TAG created and pushed successfully."