name: Create Tag at Specified Time

on:
  schedule:
    # Runs at 06:40 AM UTC on the specified date
    - cron: '40 6 4 2 *'


jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and Push Tag
        run: |
          # Ensure we are on the master branch (default branch for this repo)
          git checkout master

          # Get the latest changes
          git pull

          # Define the version number
          VERSION="v1.05"

          # Generate the tag name using the current date and version number
          TAG="rr-$(date +'%Y%m%d')-${VERSION}"

          # Create an annotated tag with a message
          git tag -a $TAG -m "Stable version for Loginform build"

          # Push the tag to the remote repository
          git push origin $TAG

          echo "Tag $TAG created and pushed successfully."
