name: Incremental Tag Creation

on:
  push:
    tags:
      - 'rr-*'

jobs:
  create-incremental-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create incremental tag
        run: |
          # Get the latest pushed tag that triggered this workflow
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo $CURRENT_TAG;
          # Extract the base part (date) and version number
          BASE_TAG=$(echo $CURRENT_TAG | sed -E 's/(.+)-v[0-9]+\.[0-9]+$/\1/')
          CURRENT_VERSION=$(echo $CURRENT_TAG | grep -oE 'v[0-9]+\.[0-9]+$')
          echo $CURRENT_VERSION;
          echo $BASE_TAG;
          # Extract major and minor version numbers
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1 | tr -d 'v')
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          
          # Increment minor version
          NEW_MINOR=$((MINOR + 1))
          NEW_TAG="${BASE_TAG}-v${MAJOR}.${NEW_MINOR}"
          
          # Create and push new tag
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
